#!/bin/bash

# System Information Report Script
# Generates a formatted system report

#Collect Data
hostname=$(hostname)
username=$(whoami)
datetime=$(date)

. /etc/os-release
os="$NAME $VERSION"

uptime_info=$(uptime -p)
cpu=$(lshw -class processor 2>/dev/null | grep "product:" | head -1 | cut -d: -f2 | xargs)
ram=$(free -h | awk '/Mem:/ {print $2}')
disks=$(lshw -class disk 2>/dev/null | grep -E "product|size" | xargs)
video=$(lshw -class display 2>/dev/null | grep "product:" | cut -d: -f2 | xargs)
host_ip=$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'src \K\S+')
gateway_ip=$(ip route | awk '/default/ {print $3}')
dns_server=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd "," -)

users_logged=$(who | awk '{print $1}' | sort | uniq | paste -sd "," -)
disk_space=$(df -h --output=target,avail -x tmpfs -x devtmpfs | tail -n +2)
process_count=$(ps -e --no-headers | wc -l)
load_averages=$(uptime | awk -F'load average: ' '{print $2}')
listening_ports=$(ss -tuln | awk 'NR>1 {print $5}' | cut -d: -f2 | sort -n | uniq | paste -sd "," -)
ufw_status=$(sudo ufw status | head -n 1)

# Output Report
echo ""
cat <<EOF
System Report for $hostname generated by $username, on $datetime

System Information
------------------
OS: $os
Uptime: $uptime_info
CPU: $cpu
RAM: $ram
Disk(s): $disks
Video: $video
Host Address: $host_ip
Gateway IP: $gateway_ip
DNS Server: $dns_server

System Status
-------------
Users Logged In: $users_logged
Disk Space:
$disk_space
Process Count: $process_count
Load Averages: $load_averages
Listening Network Ports: $listening_ports
UFW Status: $ufw_status
EOF
echo ""

